[project]
name = "pdf2md"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marker-pdf>=1.6.2",
    "streamlit>=1.45.0",
]
